#!/bin/sh
#SBATCH -J B_0004_000
#SBATCH -n 4
#SBATCH -t 8:31
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1/logs/B_0004_000.out

HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1/
srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID

echo `$ESP/bin/epoch` " START  B_0004_000   Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 4 --hostfile $HOSTFILE $ESP/bin/pchksum -v -u 5000 -t 341
echo `$ESP/bin/epoch` " FINISH B_0004_000   Seq_${SEQNUM}" >> $ESP/LOG


rm $HOSTFILE

exit
