#!/bin/sh
#SBATCH -J D_0016_001
#SBATCH -n 16
#SBATCH -t 15:1
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1/logs/D_0016_001.out

HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1/
srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID

echo `$ESP/bin/epoch` " START  D_0016_001   Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 17 --hostfile $HOSTFILE $ESP/bin/pchksum -v -u 5000 -t 601
echo `$ESP/bin/epoch` " FINISH D_0016_001   Seq_${SEQNUM}" >> $ESP/LOG


rm $HOSTFILE

exit
