#!/bin/sh
#SBATCH -J G_0008_000
#SBATCH -n 8
#SBATCH -t 33:1
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1/logs/G_0008_000.out

HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1/
srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID

echo `$ESP/bin/epoch` " START  G_0008_000   Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 8 --hostfile $HOSTFILE $ESP/bin/pchksum -v -u 5000 -t 1321
echo `$ESP/bin/epoch` " FINISH G_0008_000   Seq_${SEQNUM}" >> $ESP/LOG


rm $HOSTFILE

exit
