#!/bin/sh
#SBATCH -J G_0008_004
#SBATCH -n 8
#SBATCH -t 33:1
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1/logs/G_0008_004.out

HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1/
srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID

echo `$ESP/bin/epoch` " START  G_0008_004   Seq_${SEQNUM}" >> $ESP/LOG
 #mpirun $ESP/bin/pchksum -v -u 5000 -t 15
mpirun hostname
echo `$ESP/bin/epoch` " FINISH G_0008_004   Seq_${SEQNUM}" >> $ESP/LOG


rm $HOSTFILE

exit
