#!/bin/sh
#SBATCH -J G_0008_002-16
#SBATCH -n 10
#SBATCH -t 33:1
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1/logs/G_0008_002-16.out

env |grep SLURM
#HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
#ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1/
#ls /tmp/nodes*
#srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID
srun-16 /bin/hostname 
srun-16 sleep 20 
#srun-16 env |grep LD_LIBRARY_PATH
#srun-16 env |grep PATH
#echo `$ESP/bin/epoch` " START  G_0008_002   Seq_${SEQNUM}" >> $ESP/LOG
 mpirun $ESP/bin/pchksum -v -u 5000 -t 15
#srun-16 sleep 20
#mpirun hostname
#echo `$ESP/bin/epoch` " FINISH G_0008_002   Seq_${SEQNUM}" >> $ESP/LOG


#rm $HOSTFILE

#exit
