#!/bin/sh
#SBATCH -J H_0010_005
#SBATCH -n 10
#SBATCH -t 26:57
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1/logs/H_0010_005.out

HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1/
srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID

echo `$ESP/bin/epoch` " START  H_0010_005   Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 10 --hostfile $HOSTFILE $ESP/bin/pchksum -v -u 5000 -t 1078
echo `$ESP/bin/epoch` " FINISH H_0010_005   Seq_${SEQNUM}" >> $ESP/LOG


rm $HOSTFILE

exit
