#!/bin/sh
#SBATCH -J I_0002_008
#SBATCH -n 2
#SBATCH -t 35:57
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1/logs/I_0002_008.out

HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1/
srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID

echo `$ESP/bin/epoch` " START  I_0002_008   Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 3 --hostfile $HOSTFILE $ESP/bin/pchksum -v -u 5000 -t 1438
echo `$ESP/bin/epoch` " FINISH I_0002_008   Seq_${SEQNUM}" >> $ESP/LOG


rm $HOSTFILE

exit
