#!/bin/sh
#SBATCH -J J_0004_010
#SBATCH -n 4
#SBATCH -t 17:52
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1/logs/J_0004_010.out

HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1/
srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID

echo `$ESP/bin/epoch` " START  J_0004_010   Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 4 --hostfile $HOSTFILE $ESP/bin/pchksum -v -u 5000 -t 715
echo `$ESP/bin/epoch` " FINISH J_0004_010   Seq_${SEQNUM}" >> $ESP/LOG


rm $HOSTFILE

exit
