#!/bin/sh
#SBATCH -J B_0004_004
#SBATCH -n 4
#SBATCH -t 0:40
#SBATCH -p SUSlow
#SBATCH -o /home_nfs/georgioy/BENCHS/Light.ESP-2.2.1/logs/B_0004_004.out

ESP=/home_nfs/georgioy/BENCHS/Light.ESP-2.2.1

echo `$ESP/bin/epoch` " START  B_0004_004   Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 4 $ESP/bin/pchksum -v -u 5000 -t 27
#sleep $(( 40 * 2 / 3 ))
echo `$ESP/bin/epoch` " FINISH B_0004_004   Seq_${SEQNUM}" >> $ESP/LOG



exit
