#!/bin/sh
#SBATCH -J C_0032_002
#SBATCH -n 32
#SBATCH -t 1:7
#SBATCH -p SUSlow
#SBATCH -o /home_nfs/georgioy/BENCHS/Light.ESP-2.2.1/logs/C_0032_002.out

ESP=/home_nfs/georgioy/BENCHS/Light.ESP-2.2.1

echo `$ESP/bin/epoch` " START  C_0032_002   Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 32 $ESP/bin/pchksum -v -u 5000 -t 45
#sleep $(( 67 * 2 / 3 ))
echo `$ESP/bin/epoch` " FINISH C_0032_002   Seq_${SEQNUM}" >> $ESP/LOG



exit
