#!/bin/sh
#SBATCH -J G_0008_003
#SBATCH -n 8
#SBATCH -t 2:46
#SBATCH -p SUSlow
#SBATCH -o /home_nfs/georgioy/BENCHS/Light.ESP-2.2.1/logs/G_0008_003.out

ESP=/home_nfs/georgioy/BENCHS/Light.ESP-2.2.1

echo `$ESP/bin/epoch` " START  G_0008_003   Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 8 $ESP/bin/pchksum -v -u 5000 -t 111
#sleep $(( 166 * 2 / 3 ))
echo `$ESP/bin/epoch` " FINISH G_0008_003   Seq_${SEQNUM}" >> $ESP/LOG



exit
