#!/bin/sh
#SBATCH -J H_0010_004
#SBATCH -n 10
#SBATCH -t 2:13
#SBATCH -p SUSlow
#SBATCH -o /home_nfs/georgioy/BENCHS/Light.ESP-2.2.1/logs/H_0010_004.out

ESP=/home_nfs/georgioy/BENCHS/Light.ESP-2.2.1

echo `$ESP/bin/epoch` " START  H_0010_004   Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 10 $ESP/bin/pchksum -v -u 5000 -t 89
#sleep $(( 133 * 2 / 3 ))
echo `$ESP/bin/epoch` " FINISH H_0010_004   Seq_${SEQNUM}" >> $ESP/LOG



exit
