#!/bin/sh
#SBATCH -J I_0002_002
#SBATCH -n 2
#SBATCH -t 2:58
#SBATCH -p SUSlow
#SBATCH -o /home_nfs/georgioy/BENCHS/Light.ESP-2.2.1/logs/I_0002_002.out

ESP=/home_nfs/georgioy/BENCHS/Light.ESP-2.2.1

echo `$ESP/bin/epoch` " START  I_0002_002   Seq_${SEQNUM}" >> $ESP/LOG
# mpirun -np 2 $ESP/bin/pchksum -v -u 5000 -t 119
sleep $(( 178 * 2 / 3 ))
echo `$ESP/bin/epoch` " FINISH I_0002_002   Seq_${SEQNUM}" >> $ESP/LOG



exit
