#!/bin/sh
#SBATCH -J J_0004_023
#SBATCH -n 4
#SBATCH -t 1:30
#SBATCH -p SUSlow
#SBATCH -o /home_nfs/georgioy/BENCHS/Light.ESP-2.2.1/logs/J_0004_023.out

ESP=/home_nfs/georgioy/BENCHS/Light.ESP-2.2.1

echo `$ESP/bin/epoch` " START  J_0004_023   Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 4 $ESP/bin/pchksum -v -u 5000 -t 60
#sleep $(( 90 * 2 / 3 ))
echo `$ESP/bin/epoch` " FINISH J_0004_023   Seq_${SEQNUM}" >> $ESP/LOG



exit
