#!/bin/sh
#SBATCH -J B_0016_003
#SBATCH -n 16
#SBATCH -t 8:31
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1-cuzco/logs/B_0016_003.out

#HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1-cuzco/
#srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID

echo `$ESP/bin/epoch` " START  B_0016_003 on $SLURM_JOB_NODELIST  Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 17 $ESP/bin/pchksum -v -u 5000 -t 341
echo `$ESP/bin/epoch` " FINISH B_0016_003   Seq_${SEQNUM}" >> $ESP/LOG


rm $HOSTFILE

exit
