#!/bin/sh
#SBATCH -J G_0032_003
#SBATCH -n 32
#SBATCH -t 33:1
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1-cuzco/logs/G_0032_003.out

#HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1-cuzco/
#srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID

echo `$ESP/bin/epoch` " START  G_0032_003 on $SLURM_JOB_NODELIST  Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 32 $ESP/bin/pchksum -v -u 5000 -t 1321
echo `$ESP/bin/epoch` " FINISH G_0032_003   Seq_${SEQNUM}" >> $ESP/LOG


rm $HOSTFILE

exit
