#!/bin/sh
#SBATCH -J J_0016_007
#SBATCH -n 16
#SBATCH -t 17:52
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1-cuzco/logs/J_0016_007.out

#HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1-cuzco/
#srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID

echo `$ESP/bin/epoch` " START  J_0016_007 on $SLURM_JOB_NODELIST  Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 17 $ESP/bin/pchksum -v -u 5000 -t 715
echo `$ESP/bin/epoch` " FINISH J_0016_007   Seq_${SEQNUM}" >> $ESP/LOG


rm $HOSTFILE

exit
