#!/bin/sh
#SBATCH -J L_0032_032
#SBATCH -n 32
#SBATCH -t 9:13
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1-cuzco/logs/L_0032_032.out

#HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1-cuzco/
#srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID

echo `$ESP/bin/epoch` " START  L_0032_032 on $SLURM_JOB_NODELIST  Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 32 $ESP/bin/pchksum -v -u 5000 -t 369
echo `$ESP/bin/epoch` " FINISH L_0032_032   Seq_${SEQNUM}" >> $ESP/LOG


rm $HOSTFILE

exit
