#!/bin/sh
#SBATCH -J M_0064_008
#SBATCH -n 64
#SBATCH -t 4:48
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1-cuzco/logs/M_0064_008.out

#HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1-cuzco/
#srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID

echo `$ESP/bin/epoch` " START  M_0064_008 on $SLURM_JOB_NODELIST  Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 64 $ESP/bin/pchksum -v -u 5000 -t 192
echo `$ESP/bin/epoch` " FINISH M_0064_008   Seq_${SEQNUM}" >> $ESP/LOG


rm $HOSTFILE

exit
