#!/bin/sh
#SBATCH -J Z_0256_000
#SBATCH -n 256
#SBATCH -t 2:30
#SBATCH -o /home_nfs/georgioy/BENCHS/esp-2.2.1-cuzco/logs/Z_0256_000.out

#HOSTFILE="/tmp/nodes.$SLURM_JOB_ID"
ESP=/home_nfs/georgioy/BENCHS/esp-2.2.1-cuzco/
#srun -l /bin/hostname | sort -n | awk '{print $2}' > /tmp/nodes.$SLURM_JOB_ID

echo `$ESP/bin/epoch` " START  Z_0256_000 on $SLURM_JOB_NODELIST  Seq_${SEQNUM}" >> $ESP/LOG
 mpirun -np 256 $ESP/bin/pchksum -v -u 5000 -t 100
echo `$ESP/bin/epoch` " FINISH Z_0256_000   Seq_${SEQNUM}" >> $ESP/LOG


rm $HOSTFILE

exit
